export {default as Home} from './Home'
export {default as Monitor} from './Monitor'
export {default as Settings} from './Settings'
export {default as Error} from './Error'
export {default as CurrentDevice} from './CurrentDevice'